apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-es-data
  namespace: {{ .Values.namespace }}
spec:
  serviceName: elasticsearch-data
  replicas: {{ .Values.data.replicaCount }}
  selector:
    matchLabels:
      app: elasticsearch-data
  template:
    metadata:
      labels:
        app: elasticsearch-data
    spec:
      containers:
      - name: elasticsearch
        image: {{ .Values.elasticsearch.image }}
        resources: {{ toYaml .Values.elasticsearch.resources | nindent 12 }}
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        env:
        - name: cluster.name
          value: {{ .Values.elasticsearch.clusterName }}
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: discovery.seed_hosts
          value: {{ .Values.elasticsearch.seedHosts }}
        - name: node.master
          value: "false"
        - name: node.data
          value: "true"
        - name: ES_JAVA_OPTS
          value: {{ .Values.elasticsearch.javaOpts }}
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: elasticsearch-data
    spec:
      accessModes: {{ .Values.data.volumeClaim.accessModes | toYaml | nindent 10 }}
      resources:
        requests:
          storage: {{ .Values.data.volumeClaim.storageSize }}
