namespace: kube-logging

replicaCount: 1

kibana:
  image: docker.elastic.co/kibana/kibana:7.2.0
  resources:
    limits:
      cpu: 1000m
    requests:
      cpu: 100m

service:
  name: kibana
  port: 5601
