apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: kibana
spec:
  ports:
  - port: {{ .Values.service.port }}
  selector:
    app: kibana
