kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.releaseName }}-fluentd
roleRef:
  kind: ClusterRole
  name: {{ .Values.releaseName }}-fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ .Values.releaseName }}-fluentd
  namespace: {{ .Values.namespace }}
