apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.releaseName }}-fluentd-configmap
  namespace: {{ .Values.namespace }}
data:
  fluentd-custom.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      format json
    </source>

    <filter kubernetes.**>
      @type parser
      key_name log
      <parse>
        @type json
      </parse>
    </filter>

    <match kubernetes.**>
      @type elasticsearch
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
      scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME'] || 'http'}"
      logstash_format true
      logstash_prefix "#{ENV['FLUENT_LOGSTASH_PREFIX'] || 'logstash'}"
      logstash_dateformat "%Y%m%d"
    </match>
