apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.releaseName }}-fluentd
  namespace: {{ .Values.namespace }}
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccount: {{ .Values.releaseName }}-fluentd
      serviceAccountName: {{ .Values.releaseName }}-fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      initContainers:
      - name: init-fluentd-config
        image: busybox:1.31
        command:
        - /bin/sh
        - -c
        - |
          mkdir -p /fluentd/etc
          cp /config/fluentd-custom.conf /fluentd/etc/fluentd-custom.conf
        volumeMounts:
        - name: fluentd-custom-config
          mountPath: /config
      containers:
      - name: fluentd
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: "{{ .Values.fluentd.elasticsearchHost }}"
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "{{ .Values.fluentd.elasticsearchPort }}"
        - name: FLUENT_ELASTICSEARCH_SCHEME
          value: "{{ .Values.fluentd.elasticsearchScheme }}"
        - name: FLUENTD_SYSTEMD_CONF
          value: "{{ .Values.fluentd.systemdConf }}"
        - name: FLUENT_CONTAINER_TAIL_EXCLUDE_PATH
          value: "{{ .Values.fluentd.containerTailExcludePath }}"
        - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
          value: "{{ .Values.fluentd.containerTailParserType }}"
        resources: {{ toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentd-custom-config
          mountPath: /fluentd/etc/fluentd-custom.conf
          subPath: fluentd-custom.conf
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentd-custom-config
        configMap:
          name: {{ .Values.releaseName }}-fluentd-configmap
